import { sql, type SQL } from "drizzle-orm";
import { customType, timestamp, uuid, type AnyPgColumn } from "drizzle-orm/pg-core";

// Conventions (ADR 0011): uuid PKs generated by PostgreSQL, timestamptz everywhere, updated_at only on
// mutable tables, organization-aware composite foreign keys.

/** PostgreSQL bytea (node-postgres reads and writes it as a Buffer). Drizzle has no built-in bytea column. */
export const bytea = customType<{ data: Buffer; driverData: Buffer }>({
  dataType() {
    return "bytea";
  },
});

export const pk = () => uuid("id").primaryKey().defaultRandom();

export const tz = (name: string) => timestamp(name, { withTimezone: true, mode: "date" });

export const createdAt = () => tz("created_at").notNull().defaultNow();

export const updatedAt = () =>
  tz("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

/** CHECK (col IN (...)) from a const list. Values are developer-defined constants, never user input. */
export function oneOf(column: AnyPgColumn, values: readonly string[]): SQL {
  const list = sql.join(
    values.map((v) => sql.raw(`'${v.replace(/'/g, "''")}'`)),
    sql`, `,
  );
  return sql`${column} IN (${list})`;
}
