import { sql } from "drizzle-orm";
import { foreignKey, index, pgTable, primaryKey, text, unique, uuid } from "drizzle-orm/pg-core";
import { contacts } from "./contacts";
import { createdAt, pk, tz, updatedAt } from "./_shared";
import { orgId } from "./organizations";

export const tags = pgTable(
  "tags",
  {
    id: pk(),
    organizationId: orgId(),
    name: text("name").notNull(),
    // Generated by PostgreSQL so the uniqueness key can never drift from the name.
    nameKey: text("name_key")
      .notNull()
      .generatedAlwaysAs(sql`lower(btrim(name))`),
    color: text("color"),
    archivedAt: tz("archived_at"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique("tags_org_id_unique").on(t.organizationId, t.id),
    unique("tags_org_name_key_unique").on(t.organizationId, t.nameKey),
  ],
);

export const contactTags = pgTable(
  "contact_tags",
  {
    organizationId: orgId(),
    contactId: uuid("contact_id").notNull(),
    tagId: uuid("tag_id").notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({
      name: "contact_tags_pk",
      columns: [t.organizationId, t.contactId, t.tagId],
    }),
    foreignKey({
      name: "contact_tags_org_contact_fk",
      columns: [t.organizationId, t.contactId],
      foreignColumns: [contacts.organizationId, contacts.id],
    }),
    foreignKey({
      name: "contact_tags_org_tag_fk",
      columns: [t.organizationId, t.tagId],
      foreignColumns: [tags.organizationId, tags.id],
    }),
    index("contact_tags_tag_idx").on(t.organizationId, t.tagId, t.contactId),
  ],
);
